### ISSUE TITLE
libdash_nvim.so, 6 no suitable image found

### ISSUE THREAD

**Issue by beauwilliams** [mrjones2014/dash.nvim#121] opened 2021-11-22 23:37 UTC
I am not sure why I am betting this error.

I have tried running `make install` inside the dash directory manually which did not fix the issue

Running OSX 10.14.5

Full error below

Error detected while processing function <SNR>97_dash_nvim_search:
line    4:
E5108: Error executing lua .../site/pack/packer/start/impatient.nvim/lua/impatient.lua:186: dlopen(/Users/admin/.local/share/nvim/site/pack/packer/start/dash.nvim/lua/libdash_nvim.so, 6): no suitable imag
e found.  Did find:
        /Users/admin/.local/share/nvim/site/pack/packer/start/dash.nvim/lua/libdash_nvim.so: cannot load 'libdash_nvim.so' (load command 0x80000034 is unknown)
        /Users/admin/.local/share/nvim/site/pack/packer/start/dash.nvim/lua/libdash_nvim.so: cannot load 'libdash_nvim.so' (load command 0x80000034 is unknown)

**Comment by mrjones2014** [comment] 2021-11-23 00:52
Hmm. Are you running an M1 or Intel Mac?

What's the output of `:!uname -m` within Neovim?

The only thing I can think of that should cause this is that the incorrect architecture build of Dash.nvim is being installed. This can be caused if, for example, you're running Neovim built for Intel on an M1 Mac.

**Comment by beauwilliams** [comment] 2021-11-23 02:53
I'm running an intel mac yeah :)

Output of uname is `x86_64`

I can see the echoed output when running the make script `Installed binary for Intel architecture`

And I also tried running the commands in the bash script manually. 

It seems as far as I am aware the files are there and it seems to be the correct ones (x86)

**Comment by beauwilliams** [comment] 2021-11-23 02:58
This screenshot might come in handy. Maybe something looks out of place to you here. 

!()[https://i.ibb.co/NmqK6hq/Screen-Shot-2021-11-23-at-1-56-03-pm.png]

**Comment by mrjones2014** [comment] 2021-11-23 03:27
Hmmm. @beauwilliams are you open to installing the Rust toolchain from https://rustup.rs and attempting to build and install locally?

To do so:

1. Clone this repo
2. Update your vim config to point to the locally cloned repo file path instead of `mrjones2014/dash.nvim` (Packer supports this, not sure if others do)
3. In the repo directory, run `make clean build install`
4. Restart Neovim, run `:PackerSync` (or whatever the command is for your plugin manager), then restart Neovim again

**Comment by beauwilliams** [comment] 2021-11-23 04:37
> 

Sure no problem I can give this a shot. I will try `rm` the dash nvim folder and replace it with a clean copy of dash and then run the `make clean build install` thats usually how I do it when I test PRs submitted to some of my projects or hacking around fixing a bug on some repo. Saves time doing config changes as whatever is in /start dir is picked up automatically.

**Comment by beauwilliams** [comment] 2021-11-23 04:43
Have not written any rust in a while so I am a little.. rusty 😅 

Perhaps this is a my machine issue. But also `Could not find specification for target "aarch64-apple-darwin"`
There is an extra a in there? Perhaps a typo in the build script
![](https://i.ibb.co/51PgTjW/Screen-Shot-2021-11-23-at-3-40-37-pm.png)

**Comment by beauwilliams** [comment] 2021-11-23 04:59
I had to switch to rustc nightly using command `rustup default nightly`

But yes, Dash is now working after running `make clean build-macos-x86 install` 👍

**Comment by mrjones2014** [comment] 2021-11-23 15:47
Hmm, interesting. I'll leave this open in case anyone else is able to reproduce.

**Comment by mrjones2014** [comment] 2022-01-05 11:53
Closing since I've not seen anyone else have this issue.

**Closed by mrjones2014** 2022-01-05 11:53 UTC
Labels: bug, not-reproduced

**Comment by S1M0N38** [comment] 2022-08-05 09:52
I was able to reproduce this Issue. This is caused by [lewis6991/impatient.nvim](https://github.com/lewis6991/impatient.nvim). One optimization that impatient.nvim use to improve startup time is a [module resolution cache](https://github.com/lewis6991/impatient.nvim#implements-a-module-resolution-cache). Unfortunately, as statement in impatient.nvim README, ` This optimization breaks the loading order guarantee of the paths in 'runtimepath'`.

The solution is to disable this cache in impatient configuration: `_G.__luacache_config = { modpaths = { enable = false } }`

**Comment by mrjones2014** [comment] 2022-08-05 10:48
@S1M0N38 oh awesome, thanks for diagnosing. I’ll pin this issue in case others run into it.
