### ISSUE TITLE
"no supported fuzzy-finder plugins found"

### ISSUE THREAD

**Issue by erikw** [mrjones2014/dash.nvim#140] opened 2022-11-15 06:23 UTC
Hey,

when I run `:Dash` I get the error message

```
Error detected while processing function <SNR>42_dash_nvim_search:
line    4:
Dash.nvim: no supported fuzzy-finder plugins found.
```

This Nvim plugin used to work, I think it broke some weeks or months ago.

Specs
* Nvim: `v0.8.0` (from Homebrew)
* OS: macOS 12.6
* dash.nvim: tip of master branch (72ce1b4ad47db7a12c88fcfc61257f81d019dbd9)
* fzf-lua: tip of main branch (https://github.com/ibhagwan/fzf-lua/commit/0c6e614eeeb34ac9a7e1143861435609d1c65ba1)
* fzf: 0.34.0 (brew)

Nvim `init.vim`:

```viml
" ...

Plug 'ibhagwan/fzf-lua'
Plug 'mrjones2014/dash.nvim', { 'do': 'make install' }

" ...

lua <<EOF
require('dash').setup({})
EOF
```

Any ideas on why this plugin does not seems to be able to pick up that fzf-lua is installed? Or how I can debug this? :)

**Comment by mrjones2014** [comment] 2022-11-15 11:44
Dupe of #137

**Closed as completed by mrjones2014** 2022-11-15 11:44 UTC
